frequency: daily
datasets:
  - name: "uncached"
    source: "parsec"
    query: >
      with m as (
        select
          n.region,
          r.*,
          date_trunc('day', r.created_at) date,
          row_number() over (partition by r.cid, n.region order by r.created_at) request_number
        from retrievals_ecs r
            inner join nodes_ecs n on r.node_id = n.id
        where n.fleet = '{{ .Params.ipni }}' and r.error is null
      ), cdf as (
        select
          m.region,
          m.duration,
          cume_dist() over (partition by m.region order by m.duration) as cumedist
        from m
        where m.created_at >= {{ .StartOfWeek | timestamptz }} - '1 week'::interval
          and m.created_at < {{ .StartOfWeek | timestamptz }}
          and m.request_number = 1
      )
      select
        cdf.region,
        round(cast(cdf.duration as numeric), 4) as dur,
        round(cast(max(cdf.cumedist) as numeric), 6) as fraction
      from cdf
      group by cdf.region, dur
      having max(cdf.cumedist) <= 0.9999
      order by dur;

series:
  - type: "line"
    name: ""
    dataset: "uncached"
    labels: "dur"
    values: "fraction"
    groupfield: "region"
    groupvalue: "*"

layout:
  xaxis:
    title:
      text: "Latency in s (log scale)"
      standoff: 1
    type: "log"
  yaxis:
    autorange: true
    rangemode: "tozero"
    title:
      text: "Cumulative Fraction"
  margin:
    pad: 1
    t: 30
    l: 50
    r: 20
    b: 60
  title:
    font:
      size: 10
    text: 'Data: {{ .EndOfPreviousDay | dayModify "-7"  | simpledate}} to {{ .EndOfPreviousDay | simpledate }} ({{ .Params.ipni }}). Source: Parsec.'
    x: 1
    xanchor: "right"
    y: 0.01
    yanchor: "bottom"
