frequency: weekly
datasets:
  - name: "current"
    source: "tiros"
    query: >
      with data as (
          select
              *
          from measurements m
                   inner join runs r on r.id = m.run_id
          where m.created_at >= '2023-05-15'::timestamptz - '1 week'::interval
            and m.created_at < '2023-05-15'::timestamptz
            and m.type = '{{ .Params.type }}'
            and m.website = '{{ .Params.website}}'
      )
      SELECT
          'p' || 100*p.percentile || ' ' || sq.metric as metric_percentile,
          sq.region,
          sq.val
      FROM unnest('{0.5,0.9,0.99}'::FLOAT[]) p(percentile)
          CROSS JOIN LATERAL (
              SELECT d.region, 'ttfb' metric, percentile_cont(p.percentile)  within group (order by d.ttfb) val from data d group by d.region, d.website
              UNION
              SELECT d.region, 'fcp' metric, percentile_cont(p.percentile)  within group (order by d.fcp) val from data d group by d.region, d.website
              UNION
              SELECT d.region, 'lcp' metric, percentile_cont(p.percentile)  within group (order by d.lcp) val from data d group by d.region, d.website
              UNION
              SELECT d.region, 'cls' metric, percentile_cont(p.percentile)  within group (order by d.cls) val from data d group by d.region, d.website
          ) sq
      ORDER BY sq.metric, sq.region, sq.val;

tables:
  - type: "heatmap"
    name: "name"
    dataset: "current"
    xLabels: "region"
    yLabels: "metric_percentile"
    values: "val"
    colorbar:
      title:
        text: "Latency in s"
        side: "right"

layout:
  automargin: true
  margin:
    b: 30
  title:
    font:
      size: 10
    text: "Data: {{ .StartOfPreviousWeek | simpledate }} - {{ .EndOfPreviousWeek | simpledate }} ({{ .Params.type }})"
    x: 0.01
    xanchor: left
    'y': 0.01
    yanchor: left
  xaxis:
    title:
      text: AWS Region
    side: top
    automargin: true
  yaxis:
    title:
      text: Metric percentile
    automargin: true
  dragmode: false

config:
  modebarbuttonstoremove:
    - zoom2d
    - pan2d
    - select2d
    - lasso2d
    - zoomIn2d
    - zoomOut2d
    - autoScale2d
    - resetScale2d