frequency: daily
datasets:
  - name: "current"
    source: "tiros"
    query: >
      select
          date_trunc('day', p.created_at) date,
          count(distinct p.peer_id) filter ( where p.peer_id = any('{12D3KooWGmAkyVtRv6VKQer5JNZorty9sJQifJq6Xa7Nj7tSTzos,12D3KooWAqq9U7bd7bmoEgyKNszJ3pxnzppYdcGHch5vDzBqn5Vm,12D3KooWJVYkh57EV7vyksxVksTheTdNrtAk7yEUgJpRj9XQXhaN,12D3KooWLkmAk3MaexCmXim4h4hnBLUJtfBLmcqAfJK3KGcs8adb,12D3KooWS6RknQm8Ku36ATdbsRfcNBmzNh5JS2zGD3m5zkhJEXTU,12D3KooWJQE1SyG3ohYKGsz67dAjuESkLejtta2MzbPRqAPtKwDc}'::text[]) ) fleek,
          count(distinct p.peer_id) filter ( where p.peer_id = any('{12D3KooWRNijznEQoXrxBeNLb2TqbSFm8gG8jKtfEsbC1C9nPqce,12D3KooWCrBiagtZMzpZePCr1tfBbrZTh4BRQf7JurRqNMRi8YHF,12D3KooWDpp7U7W9Q8feMZPPEpPP5FKXTUakLgnVLbavfjb9mzrT,12D3KooWHVXoJnv2ifmr9K6LWwJPXxkfvzZRHzjiTZMvybeTnwPy,12D3KooWEDBLgMaCr6ZFwjDXr7eMXzb7s7SnHJHrYRYWYbQSxMif,12D3KooWQHS83N7ykf2pJMBSjsDMtyv5MrEukHdoiCJke2e6GjFf,12D3KooWJXVWMbcxGh2jkPiw3pjZTmB78jSQja3ke7n6vQ1y2Jdi}'::text[]) ) collab
      from providers p
      where p.created_at >= {{ .StartOfDay | timestamptz }} - '30d'::interval
        and p.created_at < {{ .StartOfDay | timestamptz }}
        and p.website = '{{ .Params.website }}'
      group by date_trunc('day', p.created_at)
      order by 1

series:
  - type: "bar"
    name: "Collab"
    dataset: "current"
    labels: "date"
    values: "collab"
  - type: "bar"
    name: "Fleek"
    dataset: "current"
    labels: "date"
    values: "fleek"

layout:
  legend:
    orientation: "h"
    x: 0.01
    y: 1.05
    xanchor: "left"
  yaxis:
    title:
      text: "Providing PeerIDs / day"
  margin:
    pad: 1
    t: 20
    l: 50
    r: 60
    b: 60
  title:
    font:
      size: 10
    text: "({{ .Params.website }})"
    x: 1
    xanchor: "right"
    y: 0.01
    yanchor: "bottom"
