frequency: daily
datasets:
  - name: "current"
    source: "tiros"
    query: >
      with percentiles as (select generate_series(30, 90, 10) val)
        select
            val,
            data.region,
            data.ratio
        from percentiles
        cross join lateral (
            select
                r.region,
                percentiles.val::float/100 percentile,
                coalesce(extract('epoch' from percentile_disc(percentiles.val::float/100) within group ( order by m.{{ .Params.metric }} ) filter ( where m.type = 'KUBO' )) /
                extract('epoch' from percentile_disc(percentiles.val::float/100) within group ( order by m.{{ .Params.metric }} ) filter ( where m.type = 'HTTP' )), -1) ratio
            from measurements m
                     inner join runs r on r.id = m.run_id
            where m.created_at >= {{ .StartOfDay | timestamptz }} - '1 week'::interval
              and m.created_at < {{ .StartOfDay | timestamptz }}
              and m.website = '{{ .Params.website }}'
              and m.status_code >= 200
              and m.status_code < 400
            group by r.region
        ) data;

tables:
  - type: "heatmap"
    name: "name"
    dataset: "current"
    xLabels: "region"
    yLabels: "val"
    values: "ratio"
    colorbar:
      title:
        text: "← Kubo faster | HTTP faster →"
        side: "right"

layout:
  automargin: true
  margin:
    b: 30
  title:
    font:
      size: 10
    text: 'Data: {{ .EndOfPreviousDay | dayModify "-7"  | simpledate}} - {{ .EndOfPreviousDay | simpledate }} ({{ .Params.metric }}, {{ .Params.website }}). Source: Tiros.'
    x: 1
    xanchor: "right"
    y: 0.01
    yanchor: "bottom"
  xaxis:
    title:
      text: AWS Region
    side: top
    automargin: true
  yaxis:
    title:
      text: Percentile
    automargin: true
  dragmode: false

config:
  modebarbuttonstoremove:
    - zoom2d
    - pan2d
    - select2d
    - lasso2d
    - zoomIn2d
    - zoomOut2d
    - autoScale2d
    - resetScale2d


