default: "004488"
colors:
  - name: offline
    color: BBBBBB
  - name: mostlyoffline
    color: EECC66
  - name: mostlyonline
    color: 6699cc
  - name: online
    color: 004488
  - name: lightyellow
    color: "EECC66"
  - name: yellow
    color: "997700"
  - name: lightred
    color: "EE99AA"
  - name: red
    color: "994455"
  - name: lightblue
    color: "6699cc"
  - name: blue
    color: "004488"
  - name: lightgreen
    color: "44AA99"
  - name: green
    color: "117733"
  - name: grey
    color: "BBBBBB"
