frequency: weekly
datasets:
  - name: "historic"
    source: "static"
    query: >
      {
        "x": [
          "2021-02-12T00:00:00Z",
          "2021-02-19T00:00:00Z",
          "2021-02-26T00:00:00Z",
          "2021-03-05T00:00:00Z",
          "2021-03-12T00:00:00Z",
          "2021-03-19T00:00:00Z",
          "2021-03-26T00:00:00Z",
          "2021-04-02T00:00:00Z",
          "2021-04-09T00:00:00Z",
          "2021-04-16T00:00:00Z",
          "2021-04-23T00:00:00Z",
          "2021-04-30T00:00:00Z",
          "2021-05-07T00:00:00Z",
          "2021-05-14T00:00:00Z",
          "2021-05-21T00:00:00Z",
          "2021-05-28T00:00:00Z",
          "2021-06-04T00:00:00Z",
          "2021-06-11T00:00:00Z",
          "2021-06-18T00:00:00Z",
          "2021-06-25T00:00:00Z",
          "2021-07-02T00:00:00Z",
          "2021-07-09T00:00:00Z",
          "2021-07-16T00:00:00Z",
          "2021-07-23T00:00:00Z",
          "2021-07-30T00:00:00Z",
          "2021-08-06T00:00:00Z",
          "2021-08-13T00:00:00Z",
          "2021-08-20T00:00:00Z",
          "2021-08-27T00:00:00Z",
          "2021-09-03T00:00:00Z",
          "2021-09-10T00:00:00Z",
          "2021-09-17T00:00:00Z",
          "2021-09-24T00:00:00Z",
          "2021-10-01T00:00:00Z",
          "2021-10-08T00:00:00Z",
          "2021-10-15T00:00:00Z",
          "2021-10-22T00:00:00Z",
          "2021-10-29T00:00:00Z",
          "2021-11-05T00:00:00Z",
          "2021-11-12T00:00:00Z",
          "2021-11-19T00:00:00Z",
          "2021-11-26T00:00:00Z",
          "2021-12-03T00:00:00Z",
          "2021-12-10T00:00:00Z",
          "2021-12-17T00:00:00Z",
          "2021-12-24T00:00:00Z",
          "2021-12-31T00:00:00Z",
          "2022-01-07T00:00:00Z",
          "2022-01-14T00:00:00Z",
          "2022-01-21T00:00:00Z",
          "2022-01-28T00:00:00Z",
          "2022-02-04T00:00:00Z",
          "2022-02-11T00:00:00Z",
          "2022-02-18T00:00:00Z",
          "2022-02-25T00:00:00Z",
          "2022-03-04T00:00:00Z",
          "2022-03-11T00:00:00Z",
          "2022-03-18T00:00:00Z",
          "2022-03-25T00:00:00Z",
          "2022-04-01T00:00:00Z",
          "2022-04-08T00:00:00Z",
          "2022-04-15T00:00:00Z",
          "2022-04-22T00:00:00Z",
          "2022-04-29T00:00:00Z",
          "2022-05-06T00:00:00Z",
          "2022-05-13T00:00:00Z",
          "2022-05-20T00:00:00Z",
          "2022-05-27T00:00:00Z",
          "2022-06-03T00:00:00Z",
          "2022-06-10T00:00:00Z",
          "2022-06-17T00:00:00Z",
          "2022-06-24T00:00:00Z",
          "2022-07-01T00:00:00Z",
          "2022-07-08T00:00:00Z",
          "2022-07-15T00:00:00Z",
          "2022-07-22T00:00:00Z",
          "2022-07-29T00:00:00Z",
          "2022-08-05T00:00:00Z",
          "2022-08-12T00:00:00Z",
          "2022-08-19T00:00:00Z",
          "2022-08-26T00:00:00Z",
          "2022-09-02T00:00:00Z",
          "2022-09-09T00:00:00Z",
          "2022-09-16T00:00:00Z",
          "2022-09-23T00:00:00Z",
          "2022-09-30T00:00:00Z",
          "2022-10-07T00:00:00Z",
          "2022-10-14T00:00:00Z",
          "2022-10-21T00:00:00Z",
          "2022-10-28T00:00:00Z",
          "2022-11-04T00:00:00Z",
          "2022-11-11T00:00:00Z",
          "2022-11-18T00:00:00Z",
          "2022-11-25T00:00:00Z",
          "2022-12-02T00:00:00Z",
          "2022-12-09T00:00:00Z",
          "2022-12-16T00:00:00Z",
          "2022-12-23T00:00:00Z",
          "2022-12-30T00:00:00Z",
          "2023-01-06T00:00:00Z",
          "2023-01-13T00:00:00Z",
          "2023-01-20T00:00:00Z",
          "2023-01-27T00:00:00Z",
          "2023-02-03T00:00:00Z",
          "2023-02-10T00:00:00Z",
          "2023-02-17T00:00:00Z",
          "2023-02-24T00:00:00Z",
          "2023-03-03T00:00:00Z",
          "2023-03-10T00:00:00Z",
          "2023-03-17T00:00:00Z",
          "2023-03-24T00:00:00Z",
          "2023-03-31T00:00:00Z",
          "2023-04-07T00:00:00Z",
          "2023-04-14T00:00:00Z",
          "2023-04-21T00:00:00Z"
        ],
        "y": [
          1.13,
          1.08,
          1.43,
          1.59,
          1.65,
          1.69,
          1.64,
          1.66,
          1.65,
          1.52,
          1.46,
          1.42,
          1.53,
          1.59,
          1.37,
          1.56,
          1.48,
          1.42,
          1.63,
          1.54,
          1.55,
          1.48,
          1.43,
          1.21,
          1.26,
          1.46,
          1.32,
          1.28,
          1.21,
          1.23,
          1.28,
          1.32,
          1.25,
          1.23,
          1.2,
          1.21,
          1.1,
          1.07,
          1.11,
          1.14,
          1.16,
          1.12,
          1.11,
          1.01,
          0.93,
          0.90,
          0.99,
          0.89,
          0.77,
          0.70,
          0.64,
          0.71,
          0.73,
          0.63,
          0.50,
          0.51,
          0.41,
          0.51,
          0.56,
          0.83,
          0.70,
          0.67,
          0.44,
          0.45,
          0.38,
          0.37,
          0.43,
          0.43,
          0.43,
          0.49,
          0.40,
          0.40,
          0.41,
          0.40,
          0.40,
          0.39,
          0.36,
          0.40,
          0.44,
          0.40,
          0.49,
          0.41,
          0.47,
          0.39,
          0.39,
          0.48,
          0.61,
          0.47,
          0.45,
          0.40,
          0.38,
          0.46,
          0.49,
          0.52,
          0.56,
          0.52,
          0.75,
          0.85,
          0.86,
          0.91,
          0.82,
          1.07,
          1.11,
          1.04,
          0.69,
          0.65,
          0.63,
          0.58,
          0.55,
          0.558,
          0.598,
          0.591,
          0.55,
          0.542,
          0.559
        ]
      }
  - name: "parsec"
    source: "parsec"
    query: >
      with period as (
        select d::date-'1 week'::interval AS start, d::date as end, tstzrange(d::date-'1 week'::interval, d::date) as range, extract(epoch from '1 week'::interval) as duration
        from generate_series('2023-04-21 00:00:00 Z'::timestamptz, {{ .StartOfWeek | timestamptz }}, '1 week'::interval) d
      ),
      m as (
        select m1.created_at, duration
        from retrievals m1
          inner join nodes n on n.id = m1.node_id
        where m1.error is null
          and m1.rt_size > 200
          and n.instance_type = 't3.small'
        union all
        select m2.created_at, duration
        from retrievals_ecs m2
          inner join nodes_ecs n on n.id = m2.node_id
        where m2.error is null
          and m2.rt_size > 200
          and n.fleet = 'default'
      )
      select period.end::date as date, percentile_disc(0.5) within group (order by m.duration) as median
      from period, m
      where m.created_at >= period.start
        and m.created_at < period.end
      group by period.end;


series:
  - type: "line"
    fill: "tozero"
    color: "lightblue"
    name: "historic"
    dataset: "historic"
    labels: "x"
    values: "y"
  - type: "line"
    fill: "tozero"
    color: "green"
    name: "parsec"
    dataset: "parsec"
    labels: "date"
    values: "median"

layout:
  title:
    text: 'Data: 12 Feb 2021 to {{ .EndOfPreviousWeek | simpledate }}. Source: Legacy monitoring script and Parsec.'
    font:
      size: 10
    x: 0.99
    xanchor: "right"
    y: 0.01
    yanchor: "bottom"
  xaxis:
    type: "date"
    rangeselector:
      buttons:
        - label: "3m"
          count: 3
          step: "month"
          stepmode: "backward"
        - label: "6m"
          count: 6
          step: month,
          stepmode: "backward"
        - label: "1y"
          count: 1
          step: "year"
          stepmode: "backward"
        - label: "18m"
          count: 18
          step: "month"
          stepmode: "backward"
        - label: "all"
          step: "all"
    rangeslider:
      visible: true
      type: linear
      autorange: true
    range: [{{ .StartOfWeek | monthModify "-18" | isodate }},{{ .StartOfWeek | isodate }}]
  yaxis:
    autorange: true
    rangemode: "tozero"
    title:
      text: "Lookup time, 6 day rolling average (seconds)"
