frequency: daily
datasets:
  - name: "ttfb"
    source: "caracol"
    query: >
      select date, value from get_collected_values(21, {{ .StartOfDay | timestamptz }} - '90 day'::interval, {{ .StartOfDay | timestamptz }});

series:
  - type: "bar"
    name: "Total"
    dataset: "ttfb"
    labels: "date"
    values: "value"

layout:
  title:
    text: "Data (90 days up to {{ .EndOfPreviousDay | simpledate }}). Source: ipfs.io / dweb.link access logs"
    font:
      size: 10
    x: 0.99
    xanchor: "right"
    y: 0.01
    yanchor: "bottom"
  legend:
    orientation: "h"
  yaxis:
    autorange: true
    rangemode: "tozero"
    title:
      text: "p95 TTFB in ms"
